### ISSUE TITLE
School hours are long

### ISSUE THREAD

**Issue by NikiSkaarup** [CphBusCosSem2/week-4-Operating-systems#2]
:D

**Comment by kaspercphbusiness** [comment]
Thanks Niki. What we have been pondering about is how and if issues could be used here as a kind of  Question and Answer session of things related to this week's topics

**Comment by JoacimV** [comment]
yes

**Comment by emil-malmgaard-rasmussen** [comment]
# 

> [`_@****_`]([url]%28url%29)

**Comment by radeonxray** [comment]
Need 29 hour days

**Comment by JamieEgeberg** [comment]
☺☻

**Comment by NisseAnd** [comment]
la da dadi da

**Comment by bjoffk** [comment]
¯_(ツ)_/¯

**Comment by scheldejonas** [comment]
Hep @NikiSkaarup

**Comment by troelslyrn** [comment]
DicksOut4Niki

**Comment by DjKirkovic** [comment]
Fewer, smaller hand-ins please!

**Comment by Viterkim** [comment]
Det burde være ulovligt at skrive javascript

**Comment by MisterSkriver** [comment]
Bring back the weekend!

**Comment by kaspercphbusiness** [comment]
OK, it has now been shown that we are all able to comment on comments here.
