### ISSUE TITLE
zzZzz

### ISSUE THREAD

**Issue by Dezent001** [CphBusCosSem2/week-4-Operating-systems#6]
<img width="500" alt="skaermbillede 2016-09-16 kl 12 35 35" src="https://cloud.githubusercontent.com/assets/18162864/18583323/3d4b2728-7c0a-11e6-933a-94a63eda6199.png">

5 timer senere zzzZZzzz!

**Comment by Dezent001** [comment]
<img width="231" alt="skaermbillede 2016-09-16 kl 12 39 29" src="https://cloud.githubusercontent.com/assets/18162864/18583407/af9b8d36-7c0a-11e6-92c3-fb26c8e92fb2.png">

Skal det tage så lang tid at installere tomcat8?

**Comment by kaspercphbusiness** [comment]
Hej, det skal ikke tage så lang tid! Overhovedet ikke - et eller andet er gået helt i kuk.

**Comment by Thomas-Hartmann** [comment]
Løsningen er at installere haveged efter installation af Tomcat. 
• apt-get install haveged
Grunden er at Tomcat har brug for data til at generere random numbers til brug for kryptering. Dette kan lede til meget lange startup tider. Se dette link for mere info:
http://www.issihosts.com/haveged/
